# Generated by Django 4.1.1 on 2022-09-22 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0002_remove_all_ips_abuse_confidence_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 14, 16, 57, 875311)),
        ),
        migrations.AlterField(
            model_name='malicious_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 14, 16, 57, 875311)),
        ),
    ]
