# Generated by Django 4.1.1 on 2022-09-30 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0003_alter_all_ips_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hashes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=101, unique=True)),
                ('type_description', models.CharField(max_length=100, null=True, unique=True)),
                ('meaningful_name', models.CharField(max_length=100, null=True)),
                ('count', models.IntegerField(null=True)),
                ('harmless_votes', models.IntegerField(null=True)),
                ('malicious_votes', models.IntegerField(null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2022, 9, 30, 19, 56, 9, 967666))),
            ],
        ),
        migrations.AlterField(
            model_name='all_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 19, 56, 9, 967666)),
        ),
        migrations.AlterField(
            model_name='malicious_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 19, 56, 9, 967666)),
        ),
    ]
