# Generated by Django 4.1.1 on 2022-10-01 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0007_alter_all_ips_date_time_alter_hashes_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashes',
            name='copyright',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hashes',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hashes',
            name='file_version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='all_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 15, 34, 11, 350306)),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 15, 34, 11, 351305)),
        ),
        migrations.AlterField(
            model_name='malicious_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 15, 34, 11, 351305)),
        ),
    ]
