# Generated by Django 4.1.1 on 2022-10-01 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0008_hashes_copyright_hashes_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashes',
            name='original_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='all_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 15, 45, 38, 292400)),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 15, 45, 38, 292400)),
        ),
        migrations.AlterField(
            model_name='malicious_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 15, 45, 38, 292400)),
        ),
    ]
