# Generated by Django 4.1.1 on 2022-10-03 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0009_hashes_original_name_alter_all_ips_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 17, 8, 19, 476500)),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='copyright',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 17, 8, 19, 476500)),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='hash',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='meaningful_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='original_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='type_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='malicious_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 17, 8, 19, 476500)),
        ),
    ]
