# Generated by Django 4.1.1 on 2022-10-06 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0011_failed_scanned_hash_alter_all_ips_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashes',
            name='last_analysis_stats',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hashes',
            name='sign_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hashes',
            name='votes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='all_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 13, 40, 3, 417071)),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 13, 40, 3, 417071)),
        ),
        migrations.AlterField(
            model_name='malicious_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 13, 40, 3, 417071)),
        ),
    ]
