# Generated by Django 4.1.1 on 2022-10-06 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0012_hashes_last_analysis_stats_hashes_sign_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 13, 44, 33, 205477)),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 13, 44, 33, 206484)),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='last_analysis_stats',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='sign_info',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='votes',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='malicious_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 13, 44, 33, 206484)),
        ),
    ]
