# Generated by Django 4.1.1 on 2022-10-06 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0018_remove_hashes_sign_info_alter_all_ips_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashes',
            name='signature_info',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='all_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 14, 35, 29, 314968)),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 14, 35, 29, 315966)),
        ),
        migrations.AlterField(
            model_name='malicious_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 14, 35, 29, 314968)),
        ),
    ]
