# Generated by Django 4.1.1 on 2022-10-06 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0026_hashes_complete_json_alter_all_ips_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashes',
            name='complete_json',
        ),
        migrations.AlterField(
            model_name='all_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 17, 30, 47, 787285)),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 17, 30, 47, 788313)),
        ),
        migrations.AlterField(
            model_name='malicious_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 17, 30, 47, 788313)),
        ),
    ]
