# Generated by Django 4.1.1 on 2022-10-07 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0027_remove_hashes_complete_json_alter_all_ips_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ip_addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('network', models.CharField(max_length=20, unique=True)),
                ('count', models.IntegerField(null=True)),
                ('last_analysis_stats', models.JSONField(null=True)),
                ('total_votes', models.JSONField(null=True)),
                ('tags', models.JSONField(null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2022, 10, 7, 20, 33, 19, 228109))),
            ],
        ),
        migrations.AlterField(
            model_name='all_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 20, 33, 19, 227102)),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 20, 33, 19, 228109)),
        ),
        migrations.AlterField(
            model_name='malicious_ips',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 20, 33, 19, 228109)),
        ),
    ]
