# Generated by Django 4.1.1 on 2022-10-08 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0032_ip_addresses_country_ip_addresses_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 12, 18, 43, 749419)),
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 12, 18, 43, 749419)),
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='owner',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
