# Generated by Django 4.1.1 on 2022-10-08 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0033_alter_hashes_date_time_alter_ip_addresses_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_addresses',
            name='tags',
        ),
        migrations.AddField(
            model_name='ip_addresses',
            name='regional_internet_registry',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 16, 26, 34, 109882)),
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 16, 26, 34, 109882)),
        ),
    ]
