# Generated by Django 4.1.1 on 2022-12-16 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0036_alter_hashes_date_time_alter_ip_addresses_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 16, 43, 27, 667832)),
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 16, 43, 27, 667832)),
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='ip',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='network',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='regional_internet_registry',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
