# Generated by Django 4.1.1 on 2022-12-17 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0037_alter_hashes_date_time_alter_ip_addresses_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 17, 30, 18, 207911)),
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 17, 30, 18, 207911)),
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='network',
            field=models.CharField(max_length=100),
        ),
    ]
