# Generated by Django 4.1.1 on 2023-03-01 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0046_failed_scanned_hash_date_time_alter_hashes_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failed_scanned_hash',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 19, 48, 45, 986366)),
        ),
        migrations.AlterField(
            model_name='hashes',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 19, 48, 45, 986366)),
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 19, 48, 45, 985325)),
        ),
    ]
