# Generated by Django 4.1.1 on 2022-09-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vt_apis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
    ]
