# Generated by Django 4.1.1 on 2022-09-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='abuseipdb_apis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
    ]
