# Generated by Django 4.1.1 on 2022-10-10 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuseipdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='failed_scanned_ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('error_message', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ip_addresses',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 16, 53, 1, 514817)),
        ),
    ]
