# Generated by Django 4.1.1 on 2022-12-16 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuseipdb', '0002_failed_scanned_ip_alter_ip_addresses_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_addresses',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 16, 43, 27, 670901)),
        ),
    ]
