# Generated by Django 4.1.1 on 2023-02-02 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuseipdb', '0012_alter_ip_addresses_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_addresses',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 17, 11, 35, 521390)),
        ),
    ]
